### ISSUE TITLE
Thinking about scopes at orga level

### ISSUE THREAD

**Issue by XavierJp** [datagouv/d-roles#24]
## Implementation

This require some in depth analysis : 
- can we add a organisation_service_provider_relation ? 
- how does this run with the parent_child_relation ? 

### first implementation idea 

We could simply expose scopes per level (group, organisation) when we retrieve a user for a given service provider :

```
  email: geoffrey@data.gouv.fr
  groups:
    - name: operateur
      scopes: read-only
    - name: data
      scopes: maintainer
  organizationscopes: read-only 
```
In this scenario, Geoffrey has different scopes on our service provider, and we would let the service provider decide what to do with these

### second implementation idea 

Same scenario, but now our solution is to merge scopes : 
```
  email: geoffrey@data.gouv.fr
  scopes: read-only maintainer read-only
```
In this scenario Geoffrey inherit from both its groups and its organization. The issue is, for d-roles, every scopes are just a string, there is no hierarchy, so we cannont say that `maintainer` includes `read-only` and therefore that `read-only` can be ignored.

Because of this I advocate against the scope merging solution and prefer the first solution (so far).  

### users - orga relation 

Users are not clearly linked to an orga. There are several way to get the orga : 
- the orga of every groups a user belongs to : does this mean a user belong to several orga ?
- the siren from proconnect : but this is notoriously unthrusthworthy
- or we can force the link siren/user but with no way to ensure data quality

**Comment by XavierJp** [comment]
I believe that the lack of good user-orga relation is a big risk for this feature. 

The most interesting lead is to get the user org from it's groups, but this advocate against first implem. It suggest a new implementation. Orga level scopes will rather be set at group level : 

```
  name: "equipe data"
  user:
    - email: geoffrey
  scopes: # here are the specific scope a group has on a service provider
  organization: 
       siren: 000344003
	   scopes: # there are the organisation level scopes
```

In this implem, should a group with no scopes still get returned as it inherits from organisation scopes ?

It would create security issues. As it would mean that granting an organisation access to a service provider would grant the service provider access (read but also right acces) to every child groups

Last implem is the most naive. We only create a `/organisation` route and it can return organisation scope. This route would be a bit distinct from the others and would be meant to work independantly from the group/user logic. 

I think that in terms of devX in is not the best for the service providers as it will force them to both check the rights at user level and at org level. But I  believe we can think of a smoother approach. And I dont see major drawbacks in terms of architecture or security so this might be the best solution.
